Add functionality to set log level for all request logs
SAP/cf-nodejs-logging-support pull request #78
Opened 2021-06-09 16:10 UTC by nicklas-dohrn

Adds functionality to set request logging level globally

2021-06-15 10:55 UTC, christiand93 requested changes
We should have a small section in README.md to document the new `setRequestLogLevel` function.

2021-06-15 10:55 UTC, christiand93 commented on core/log-core.js
> +var reqestLogLevel = "info";
reqestLogLevel --> requestLogLevel

2021-06-16 08:45 UTC, nicklas-dohrn commented
Added documentation for the new feature

2021-06-16 09:16 UTC, christiand93 approved these changes
LGTM  👍

2021-06-16 09:16 UTC, christiand93 commented on README.md
> +the default log level for request logs is ``info``
```suggestion
The default log level for request logs is ``info``.
```

2021-06-16 16:52 UTC, merged